/**
 * LOADIT DATA ROOM NDA — single source of truth for the click-through
 * confidentiality agreement. The gate renders these clauses and records
 * acceptance against NDA_VERSION; the reference PDF in the room is generated
 * from the same content. Bump NDA_VERSION to force re-acceptance.
 */
export const NDA_VERSION = "v1";
export const NDA_EFFECTIVE = "September 27, 2026";
export const NDA_TITLE = "Loadit Data Room — Confidentiality & Non-Disclosure Agreement";
export const NDA_INTRO = "By clicking \"I Agree,\" you (the \"Recipient\") enter into this Confidentiality and Non-Disclosure Agreement (this \"Agreement\") with Loadit Inc., a Delaware corporation (\"Loadit\" or the \"Company\"), effective on the date and time of your acceptance. If you are accepting on behalf of an entity, you represent that you are authorized to bind that entity, and \"Recipient\" refers to both you and that entity. Read this Agreement in full before accepting; access to the Loadit diligence data room (the \"Data Room\") is granted only on these terms.";
export interface NdaClause { heading: string; body: string; }
export const NDA_CLAUSES: NdaClause[] = [
  { heading: "1. Purpose", body: "Loadit is granting the Recipient access to the Data Room and the materials in it so the Recipient may evaluate a possible investment in, financing of, or business relationship with Loadit (the \"Permitted Purpose\"). The Recipient may use the Data Room and its contents only for the Permitted Purpose." },
  { heading: "2. Confidential Information", body: "\"Confidential Information\" means all non-public information disclosed by or on behalf of Loadit to the Recipient, whether before or after acceptance, in any form, that is marked confidential or that a reasonable person would understand to be confidential given its nature and the circumstances. It includes, without limitation: (a) business plans, strategies, forecasts, and models; (b) financial information, pricing, budgets, and projections; (c) customer, client, vendor, and partner lists and related information; (d) marketing, research, and competitive analyses; (e) product concepts, designs, specifications, roadmaps, and prototypes; (f) software, source code, algorithms, systems, and technical data; (g) inventions, intellectual property, trade secrets, know-how, and proprietary processes; (h) every document and file contained in the Data Room; and (i) the existence, nature, and status of any discussions, and the identity and terms of any partner, counterparty, or transaction referenced in the Data Room." },
  { heading: "3. Obligations of the Recipient", body: "The Recipient shall: (a) protect the Confidential Information using at least a reasonable standard of care; (b) not disclose it to any third party without Loadit's prior written consent, except to the Recipient's employees, advisors, or agents who need it for the Permitted Purpose and who are bound by confidentiality obligations no less protective than these; (c) use it solely for the Permitted Purpose and for no competitive, personal, or third-party benefit; (d) not copy, screenshot, download, forward, or redistribute materials except as reasonably necessary for the Permitted Purpose; (e) promptly notify Loadit of any unauthorized use or disclosure and cooperate to remedy it; (f) be responsible for any breach by its representatives; and (g) upon Loadit's request, promptly return or permanently destroy all Confidential Information, including copies and derivatives, and certify destruction if asked." },
  { heading: "4. Exclusions", body: "Confidential Information does not include information the Recipient can show through written records (a) is or becomes public through no fault of the Recipient; (b) was lawfully known to the Recipient before disclosure; (c) is lawfully received from a third party without breach of a confidentiality obligation; or (d) is independently developed by the Recipient without use of or reference to the Confidential Information." },
  { heading: "5. Term and Survival", body: "This Agreement is effective on acceptance and continues until terminated by Loadit. The Recipient's confidentiality obligations survive for five (5) years from the date of acceptance; obligations relating to trade secrets survive for as long as the information remains a trade secret under applicable law." },
  { heading: "6. No Offer; No Obligation", body: "The Data Room and its contents are provided for information only. Nothing in the Data Room is an offer to sell or a solicitation to buy any security, and nothing here is investment, legal, tax, or accounting advice. Access does not obligate either party to proceed with any transaction; any transaction will be governed by a separate definitive written agreement signed by both parties." },
  { heading: "7. Non-Circumvention", body: "For two (2) years from acceptance, the Recipient shall not use the Confidential Information to circumvent Loadit or to contact, solicit, or transact directly with any partner, counterparty, vendor, or customer first identified to the Recipient through the Data Room, except through Loadit or with Loadit's prior written consent." },
  { heading: "8. No License", body: "Nothing in this Agreement grants the Recipient any license or ownership interest in Loadit's Confidential Information or intellectual property, by implication or otherwise, except the limited right to review for the Permitted Purpose." },
  { heading: "9. No Warranty; Forward-Looking Statements", body: "The Confidential Information is provided \"as is.\" Loadit makes no warranty as to its accuracy or completeness. Projections, estimates, and forward-looking statements are illustrative and not guarantees. References to \"patent pending\" mean applications filed, not patents granted. Any retail cash-in capability described is in certification and not live. The Recipient will make its own independent evaluation." },
  { heading: "10. Injunctive Relief", body: "The Recipient agrees that unauthorized use or disclosure of Confidential Information may cause Loadit irreparable harm for which money damages are inadequate, and that Loadit is entitled to seek injunctive or equitable relief in addition to any other remedy, without posting bond." },
  { heading: "11. Governing Law", body: "This Agreement is governed by the laws of the State of Delaware, without regard to conflict-of-laws principles. The parties consent to the exclusive jurisdiction and venue of the state and federal courts located in Delaware." },
  { heading: "12. Electronic Acceptance", body: "By entering the Recipient's name and email and clicking \"I Agree,\" the Recipient signs this Agreement electronically and intends that click to be a legally binding signature under the U.S. E-SIGN Act and comparable law. Loadit records the Recipient's name, email, and the date and time of acceptance as evidence of this Agreement." },
  { heading: "13. General", body: "This Agreement is the entire agreement between the parties on its subject matter and supersedes prior understandings. If any provision is unenforceable, the rest remains in effect. No waiver is effective unless in writing. The Recipient may not assign this Agreement without Loadit's consent." },
];
